version: 2

sources:
    - name: northwind_etl
      tables: 
        - name: orders
        - name: customers
          description: Essa é a tabela de clientes
          columns:
            - name: customer_id
              description: id do cliente
              tests:
                - unique
                - not_null
        - name: products
          description: Essa é a tabela de produtos
          columns:
            - name: product_id
              description: id do produto
              tests:
                - unique
                - not_null
        - name: shippers
          description: Essa é a tabela de transportadores
          columns:
            - name: shipper_id
              description: id da transporadora
              tests:
                - unique
                - not_null
        - name: suppliers
          description: Essa é a tabela de fornecedores
          columns:
            - name: supplier_id
              description: id do forncedor
              tests:
                - unique
                - not_null
        - name: employees
          description: Essa é a tabela de funcionarios
          columns:
            - name: employee_id
              description: id do funcionario
              tests:
                - unique
                - not_null
        - name: order_details
          description: Essa é a tabela de detalhes do pedido
          columns:
            - name: product_id
              description: id do funcionario
              tests:
                - unique
                - not_null